plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

def localProps = new Properties()
def localFile = rootProject.file('local.properties')
if (localFile.exists()) {
    localFile.withInputStream { localProps.load(it) }
}

android {
    namespace 'com.geeui.face'
    compileSdk 36

    defaultConfig {
        applicationId "com.geeui.face"
        minSdk 30
        targetSdk 36
        versionCode 202402161
        versionName "1.1."+versionCode
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    signingConfigs {
        if (localProps['STORE_PASSWORD'] && localProps['KEY_PASSWORD']) {
            config {
                storeFile file(localProps['STORE_FILE'] ?: './letianpai.jks')
                keyAlias localProps['KEY_ALIAS'] ?: 'letianpai'
                keyPassword localProps['KEY_PASSWORD']
                storePassword localProps['STORE_PASSWORD']
            }
        }
    }

    buildTypes {
        debug {
            if (signingConfigs.findByName('config')) {
                signingConfig signingConfigs.config
            }
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

        }
        release {
            if (signingConfigs.findByName('config')) {
                signingConfig signingConfigs.config
            }
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.media3:media3-exoplayer:1.5.1'
    implementation 'androidx.media3:media3-ui:1.5.1'
    implementation 'com.google.code.gson:gson:2.11.0'
    implementation project(path: ':CommandLib')
    implementation project(path: ':GestureFactory')
    implementation project(path: ':Components')
}
